// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1BJ23F0Bbf4qYbsuIH3TJZJs4e6mOPiI',
    appId: '1:286775143293:web:00d670ac5ca53fd6343a14',
    messagingSenderId: '286775143293',
    projectId: 'carpool-app-29f84',
    authDomain: 'carpool-app-29f84.firebaseapp.com',
    storageBucket: 'carpool-app-29f84.appspot.com',
    measurementId: 'G-5BMGNRW2QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39hCt8ReJLnMYbN7pMmud1BhEOqU5y3k',
    appId: '1:286775143293:android:c1111919eddf6444343a14',
    messagingSenderId: '286775143293',
    projectId: 'carpool-app-29f84',
    storageBucket: 'carpool-app-29f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcu74vhLSGeaAyQ_PhOL7PQlCRRBz62wM',
    appId: '1:286775143293:ios:af6b068e9d524ea5343a14',
    messagingSenderId: '286775143293',
    projectId: 'carpool-app-29f84',
    storageBucket: 'carpool-app-29f84.appspot.com',
    iosClientId:
        '286775143293-2n9eb0r72fr1mmu7r6kec3dc364osjnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.carPoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcu74vhLSGeaAyQ_PhOL7PQlCRRBz62wM',
    appId: '1:286775143293:ios:af6b068e9d524ea5343a14',
    messagingSenderId: '286775143293',
    projectId: 'carpool-app-29f84',
    storageBucket: 'carpool-app-29f84.appspot.com',
    iosClientId:
        '286775143293-2n9eb0r72fr1mmu7r6kec3dc364osjnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.carPoolApp',
  );
}
